---
title: "Projet Final"
output: html_document
date: "2023-04-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(readr)
data <- read_csv("wdbc.data", 
                 col_names = c("ID number","Diagnosis","radius_mean","texture_mean","perimeter_mean","area_mean","smoothness_mean","compactness_mean","concavity_mean","concave_points_mean","symmetry_mean","fractal_dimension_mean","radius_SE","texture_SE","perimeter_SE","area_SE","smoothness_SE","compactness_SE","concavity_SE","concave_points_SE","symmetry_SE","fractal_dimension_SE","radius_worst","texture_worst","perimeter_worst","area_worst","smoothness_worst","compactness_worst","concavity_worst","concave_points_worst","symmetry_worst","fractal_dimension_worst"))

data <- na.omit(data)

# Conversion des variables non numériques en variables numériques
data$Diagnosis <- as.numeric(factor(data$Diagnosis))

data <- scale(data)
data <- as_tibble(data)



```

Question 1 : Analyse descriptive, visualisation

analyse descriptive du dataset avec ces tableaux
```{r}
library(dplyr)
library(ggplot2)

glimpse(data)
data$Diagnosis <- as.factor(data$Diagnosis)
summary(data)
```

graphique pour montrer pertinence entre les variables ?

```{r}
ggplot(
  data = data
) +
  aes(
    x = radius_mean,
    y = perimeter_mean,
    color = Diagnosis
  ) +
  geom_point()+
  theme_classic()
```

Statistiques descriptives bivariées
```{r}
#Calcul du coefficient de régression linéaire r et de détermination R²
cor.test(data$radius_mean,data$texture_mean)
ggplot(data) +
  aes(
    x = radius_mean,
    y = texture_mean
  ) +
  geom_point()+
  theme_classic()

cor.test(data$radius_mean,data$perimeter_mean)
ggplot(data) +
  aes(
    x = radius_mean,
    y = perimeter_mean
  ) +
  geom_point()+
  theme_classic()

cor.test(data$radius_mean,data$area_mean)
ggplot(data) +
  aes(
    x = radius_mean,
    y = area_mean
  ) +
  geom_point()+
  theme_classic()
```


```{r}
\#Détermination du nombre optimal de clusters 
library(factoextra) 
fviz_nbclust(data, kmeans, method = "wss")

# Création du modèle

library(dplyr) model \<- data %\>% select(contains('\_mean')) %\>% kmeans(centers = 2)

# Visualisation des résultats

library(cluster) library(animation)

clusplot(data, model\$cluster, color = TRUE, shade = TRUE, labels = 2, lines = 0)

kmeans.ani(data)

# Interprétation des résultats

table(model\$cluster)

print(model)
```



```{r}
set.seed(123)
gap_stat <- clusGap(data, FUN = kmeans, nstart = 25,
                    K.max = 10, B = 50)

fviz_gap_stat(gap_stat)

```

```{r}
# classification ascendante hiérarchique

  

```
